export const themeJson = {
  cssVariables: {
    '--sjs-general-backcolor': 'var(--surface-color)',
    '--sjs-general-backcolor-dark': 'var(--form-bg-color)',
    '--sjs-general-backcolor-dim': 'var(--form-bg-color)',
    '--sjs-general-backcolor-dim-light': 'var(--card-bg-color)',
    '--sjs-general-backcolor-dim-dark': 'var(--surface-color)',
    '--sjs-general-forecolor': 'var(--main-font-color)',
    '--sjs-general-forecolor-light': 'var(--lighter-font-color)',
    '--sjs-general-dim-forecolor': 'var(--main-font-color)',
    '--sjs-general-dim-forecolor-light': 'var(--muted-font-color)',
    '--sjs-primary-backcolor': 'var(--primary-color)',
    '--sjs-primary-backcolor-light': 'var(--card-bg-color)',
    '--sjs-primary-backcolor-dark': 'var(--link-color)',
    '--sjs-primary-forecolor': 'var(--main-font-color-inverted)',
    '--sjs-primary-forecolor-light': 'var(--muted-font-color)',
    '--sjs-base-unit': '8px',
    '--sjs-corner-radius': '4px',
    '--sjs-secondary-backcolor': 'var(--tertiary-color)',
    '--sjs-secondary-backcolor-light': 'var(--card-bg-color)',
    '--sjs-secondary-backcolor-semi-light': 'var(--card-bg-hover-color)',
    '--sjs-secondary-forecolor': 'var(--main-font-color-inverted)',
    '--sjs-secondary-forecolor-light': 'var(--muted-font-color)',
    '--sjs-shadow-small': '0px 1px 2px 0px rgba(0, 0, 0, 0.08)',
    '--sjs-shadow-medium': '0px 2px 6px 0px rgba(0, 0, 0, 0.06)',
    '--sjs-shadow-large': '0px 8px 16px 0px rgba(0, 0, 0, 0.06)',
    '--sjs-shadow-inner': 'inset 0px 1px 2px 0px rgba(0, 0, 0, 0.08)',
    '--sjs-border-light': 'var(--border-color)',
    '--sjs-border-default': 'var(--input-border-color)',
    '--sjs-border-inside': 'var(--border-color)',
    '--sjs-special-red': 'var(--error-color)',
    '--sjs-special-red-light': 'rgba(229, 10, 62, 0.1)',
    '--sjs-special-red-forecolor': 'var(--main-font-color-inverted)',
    '--sjs-special-green': 'var(--success-color)',
    '--sjs-special-green-light': 'rgba(34, 197, 94, 0.1)',
    '--sjs-special-green-forecolor': 'var(--main-font-color-inverted)',
    '--sjs-special-blue': 'var(--secondary-color)',
    '--sjs-special-blue-light': 'rgba(18, 151, 180, 0.1)',
    '--sjs-special-blue-forecolor': 'var(--main-font-color-inverted)',
    '--sjs-special-yellow': 'var(--warning-color)',
    '--sjs-special-yellow-light': 'rgba(252, 154, 99, 0.1)',
    '--sjs-special-yellow-forecolor': 'var(--main-font-color-inverted)',
  },
  isPanelless: true,
};
