export const themeJson = {
  cssVariables: {
    '--sjs-general-backcolor': 'var(--bg-secondary)',
    '--sjs-general-backcolor-dark': 'var(--bg-secondary)',
    '--sjs-general-backcolor-dim': 'var(--bg-secondary)',
    '--sjs-general-backcolor-dim-light': 'var(--card-bg-color)',
    '--sjs-general-backcolor-dim-dark': 'var(--bg-secondary)',
    '--sjs-general-forecolor': 'var(--text-primary)',
    '--sjs-general-forecolor-light': 'var(--text-secondary)',
    '--sjs-general-dim-forecolor': 'var(--text-primary)',
    '--sjs-general-dim-forecolor-light': 'var(--text-secondary)',
    '--sjs-primary-backcolor': 'var(--accent-color)',
    '--sjs-primary-backcolor-light': 'var(--card-bg-color)',
    '--sjs-primary-backcolor-dark': 'var(--blue-primary)',
    '--sjs-primary-forecolor': 'var(--text-primary-light)',
    '--sjs-primary-forecolor-light': 'var(--text-secondary)',
    '--sjs-base-unit': '8px',
    '--sjs-corner-radius': '4px',
    '--sjs-secondary-backcolor': 'var(--yellow-primary)',
    '--sjs-secondary-backcolor-light': 'var(--card-bg-color)',
    '--sjs-secondary-backcolor-semi-light': 'var(--card-bg-hover-color)',
    '--sjs-secondary-forecolor': 'var(--text-primary-light)',
    '--sjs-secondary-forecolor-light': 'var(--text-secondary)',
    '--sjs-shadow-small': '0px 1px 2px 0px rgba(0, 0, 0, 0.08)',
    '--sjs-shadow-medium': '0px 2px 6px 0px rgba(0, 0, 0, 0.06)',
    '--sjs-shadow-large': '0px 8px 16px 0px rgba(0, 0, 0, 0.06)',
    '--sjs-shadow-inner': 'inset 0px 1px 2px 0px rgba(0, 0, 0, 0.08)',
    '--sjs-border-light': 'var(--border-color)',
    '--sjs-border-default': 'var(--input-border-color)',
    '--sjs-border-inside': 'var(--border-color)',
    '--sjs-special-red': 'var(--error-color)',
    '--sjs-special-red-light': 'rgba(161, 28, 67, 0.1)',
    '--sjs-special-red-forecolor': 'var(--text-primary-light)',
    '--sjs-special-green': 'var(--green-primary)',
    '--sjs-special-green-light': 'rgba(56, 127, 106, 0.1)',
    '--sjs-special-green-forecolor': 'var(--text-primary-light)',
    '--sjs-special-blue': 'var(--purple-secondary)',
    '--sjs-special-blue-light': 'rgba(76, 173, 233, 0.1)',
    '--sjs-special-blue-forecolor': 'var(--text-primary-light)',
    '--sjs-special-yellow': 'var(--yellow-primary)',
    '--sjs-special-yellow-light': 'rgba(249, 171, 62, 0.1)',
    '--sjs-special-yellow-forecolor': 'var(--text-primary-light)',
  },
  isPanelless: true,
};
